spring.application.name=typeahead

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Time decay: newFrequency = (frequency / factor) + todayCount
typeahead.decay.factor=10
# every day at midnight
typeahead.decay.cron=0 0 0 * * *
typeahead.trie.rebuild-ms=60000

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379